package com.agnes.blogreader

import android.os.Bundle
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.recyclerview.widget.LinearLayoutManager
import com.agnes.blogreader.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
    lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        binding.rvBlogReader.layoutManager = LinearLayoutManager(this)
        displayBlogs()
    }

    fun displayBlogs() {
        val blog1 = Blog("Agnes Auma", "", "Resilience", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog2 = Blog("Reign Kaiden", "", "Ambition", "22/10/2024", "Ambition is a strong desire for achievement, success, power, or wealth. It involves a willingness to work hard and strive to attain a particular goal or objective. Ambition can drive individuals to reach new heights, but it can also lead to negative consequences if taken to an extreme. Ambition is often associated with qualities like determination, drive, and competitiveness. However, it can also be seen as a double-edged sword, as excessive ambition can lead to unethical behavior or neglect of other important aspects of life. Overall, ambition is a complex human trait that can have both positive and negative manifestations depending on how it is channeled.", "")
        val blog3 = Blog("Muhadi Wawire", "", "Grit", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog4 = Blog("Shalom Keesi", "", "Emotional Intelligence", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog5 = Blog("Shalom Uwamahoro", "", "Fun", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog6 = Blog("Nancy Wainaina", "", "Aging Gracefully", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog7 = Blog("Priscilla Mikisa", "", "How to be rich", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog8 = Blog("Stefflon Don", "", "Brilliance", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog9 = Blog("Meghan Otieno", "", "More than ever", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")
        val blog10 = Blog("Wanja Kayago", "", "No more", "22/10/2024", "Resilience is the ability to adapt and bounce back in the face of adversity, stress, or challenging circumstances. It is the capacity to withstand, recover, and grow from difficult experiences. Resilient individuals possess a range of skills and qualities, such as emotional regulation, problem-solving, optimism, and a sense of purpose. Resilience is not about being invulnerable; it's about having the flexibility and inner strength to navigate through hardships and emerge stronger. Developing resilience can help individuals cope more effectively with life's ups and downs, fostering personal growth, well-being, and the ability to thrive in the face of adversity.", "")

        val blogList = listOf(blog1, blog2, blog3, blog4, blog5, blog6, blog7, blog8, blog9, blog10)
        val blogAdapter = BlogAdapter(blogList)
        binding.rvBlogReader.adapter = blogAdapter

    }
}



